-- MySQL Script generated by MySQL Workbench
-- Wed May 15 16:39:28 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `hero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hero` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `job` VARCHAR(45) NULL,
  `healthPoint` INT NULL,
  `attackPower` INT NULL,
  `defensePower` INT NULL,
  `position` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `offensiveEquipement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `offensiveEquipement` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  `attackPower` INT NULL,
  `Hero_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_OffensiveEquipement_Hero_idx` (`Hero_id` ASC) VISIBLE,
  CONSTRAINT `fk_OffensiveEquipement_Hero`
    FOREIGN KEY (`Hero_id`)
    REFERENCES `hero` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `defensiveEquipement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `defensiveEquipement` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  `defensePower` INT NULL,
  `Hero_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_OffensiveEquipement_Hero_idx` (`Hero_id` ASC) VISIBLE,
  CONSTRAINT `fk_OffensiveEquipement_Hero0`
    FOREIGN KEY (`Hero_id`)
    REFERENCES `hero` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `case`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `case` (
  `id` INT NOT NULL,
  `Content` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `board`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `board` (
  `id` INT NOT NULL,
  `Hero_id` INT NOT NULL,
  `case_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Hero_id`, `case_id`),
  INDEX `fk_Board_Hero1_idx` (`Hero_id` ASC) VISIBLE,
  INDEX `fk_board_case1_idx` (`case_id` ASC) VISIBLE,
  CONSTRAINT `fk_Board_Hero1`
    FOREIGN KEY (`Hero_id`)
    REFERENCES `hero` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_board_case1`
    FOREIGN KEY (`case_id`)
    REFERENCES `case` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Ennemy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Ennemy` (
  `id` INT NOT NULL,
  `Ennemy` VARCHAR(45) NULL,
  `case_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Ennemy_case1_idx` (`case_id` ASC) VISIBLE,
  CONSTRAINT `fk_Ennemy_case1`
    FOREIGN KEY (`case_id`)
    REFERENCES `case` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MysteryBox`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MysteryBox` (
  `id` INT NOT NULL,
  `item` VARCHAR(45) NULL,
  `case_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_MysteryBox_case1_idx` (`case_id` ASC) VISIBLE,
  CONSTRAINT `fk_MysteryBox_case1`
    FOREIGN KEY (`case_id`)
    REFERENCES `case` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
